# Generated by Django 2.2.17 on 2020-12-15 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18)),
                ('category', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_agent', models.CharField(max_length=150)),
                ('email', models.EmailField(default=None, max_length=254, unique=True)),
                ('telephone', models.CharField(max_length=16)),
                ('agent_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Company')),
            ],
        ),
    ]
